#!/usr/bin/env ruby
# post-receive

developer_deploy_to_dir = ''
master_deploy_to_dir = ''

def deploy(branch, deploy_to_dir, re)
	if (branch =~ re)
		deploy_to_dir = File.expand_path(deploy_to_dir)
		`GIT_WORK_TREE="#{deploy_to_dir}" git checkout -f master`
		puts "DEPLOY: master(#{to}) copied to '#{deploy_to_dir}'"
		exit
	end
end

# 1. Read STDIN (Format: "from_commit to_commit branch_name")
from, to, branch = ARGF.read.split " "

deploy(branch, developer_deploy_to_dir, /developer$/)
deploy(branch, master_deploy_to_dir, /master$/)

puts "Received branch #{branch}, not deploying."
